# netlify.toml — known-good minimal

[build]
  command  = "npm run build"
  publish  = "dist"
  functions = "functions"

# (Optional) lock Node version if you want builds to match local: 
# [build.environment]
#   NODE_VERSION = "20"

# Single-page app routing
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200
