[build]
  publish = "."
  functions = "netlify/functions"

  [build.environment]
    NODE_VERSION = "18"
    NODE_MODULES_CACHE = "true"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = []